export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const PRODUCT_RESET = "PRODUCT_RESET";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
